### PR TITLE
specs: fix order algorithm and add format spec

### LINKED ISSUE #120: Bug: Make alphabetical order spec be case insensitive.
Let's take the example of this: https://travis-ci.org/cristianoliveira/awesome4girls/builds/294426635?utm_source=github_status&utm_medium=notification

The spec is failing because while it's correct based on ASCII based order, most humans would sort it case insensitively. I think having it case insensitive would be better.

### PR DESCRIPTION
**Pull request by cristianoliveira**
Hey @harsh183 fixed #120 

Also added some new specs in order to enforce some of the formatting rules described on Contribution Guide (`CONTRIBUTION.md`)

### CODE REVIEW

File: spec/links_spec.rb [hunk 1]
```diff
@@ -1,19 +1,19 @@
...
 
 describe 'links' do
   let(:readme) { File.open("README.md").read }
-  let(:list) { AwesomeListRender.parse(readme) }
+  let(:list) { AwesomeList.parse(readme) }
 
   it 'must not appear twice' do
-    list_links = list.project_links.map { |l| l.map{|ll| ll['href'] }}.flatten
-    expect(list_links).to eq(list_links.uniq), duplicated_links_error(list_links)
+    links = list.projects.css('li a').map { |a| a['href'] }
```
Comment (harsh183) [inline spec/links_spec.rb]: Since we're repeating this line, maybe move it outside so it's common or move it to a function?

File: spec/format_spec.rb [hunk 2]
```diff
@@ -1,55 +1,86 @@
...
-            project_sort_error(list.subsection_titles[i], link_texts)
+            project_sort_error(list.subsection_titles[i-1], link_texts)
+        end
+      end
+    end
+
+    context 'descriptions' do
+      it 'must start with captalized letter' do
+        list.projects.css('li').each do |project|
+          description = project.css('p').last.text
```
Comment (harsh183) [inline spec/format_spec.rb]: this loop structure is repeated, move it outside to a function that gives an array of descriptions?

Comment (cristianoliveira) [reply spec/format_spec.rb]: We can't do it cause `project.css('p')` return 2 items and the last one is the description.

Comment (harsh183) [reply spec/format_spec.rb]: Okay, point.

Comment (cristianoliveira) [reply spec/format_spec.rb]: 👍

**Comment by harsh183** [comment]
Great to see, the repo feels much better now.
